server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://172.30.0.2:3306/jpa_test?createDatabaseIfNotExist=true&cachePrepStmts=true&useServerPrepStmts=true&rewriteBatchedStatements=true
    username: root
    password: Armin#123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 5000
        order_inserts: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true